using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GetBandName : MonoBehaviour
{

    List<string> bandNameStart;
    List<string> bandNameDecr;
    public void Awake()
    {
        bandNameStart = new List<string>();
        bandNameStart.Add("Stage Dolls");
        bandNameStart.Add("Vaishnava Jana To");
        bandNameStart.Add("Pritch & Trim");
        bandNameStart.Add("The Jazz Entertainers");
        bandNameStart.Add("The Grid");
        bandNameStart.Add("Gary Brooke");
        bandNameStart.Add("Pete 'Big Dog' Fetters");
        bandNameStart.Add("Hypp & Krimson");
        bandNameStart.Add("The Mac-O-Chee Valley Folks");
        bandNameStart.Add("Titanic");
        bandNameStart.Add("Adriena Bartosova");
        bandNameStart.Add("Joel Mabus");
        bandNameStart.Add("Kimberly Barber");
        bandNameStart.Add("Patrick Sébastien");
        bandNameStart.Add("Flying Saucer Attack");
        bandNameStart.Add("Lil' Keke");
        bandNameStart.Add("Melinda Coffey");
        bandNameStart.Add("T.T.");
        bandNameStart.Add("Buddy Clark");
        bandNameStart.Add("Bernard Dargassies");
        bandNameStart.Add("Billy Hill");
        bandNameStart.Add("Giuseppe Ottaviani");
        bandNameStart.Add("Sky Santana");
        bandNameStart.Add("Lani Hall");
        bandNameStart.Add("Ben G");
        bandNameStart.Add("Empire State Human");
        bandNameStart.Add("Bukovian Song & Dance Ensemble");
        bandNameStart.Add("Kansas City Bill & Orchestra");
        bandNameStart.Add("Min. William Tolson Jr.");
        bandNameStart.Add("Group 1850");
        bandNameStart.Add("Kenji Ozawa");
        bandNameStart.Add("Goodwill");
        bandNameStart.Add("James Douglas");
        bandNameStart.Add("Sean Harris");
        bandNameStart.Add("Susan Johnson");
        bandNameStart.Add("George Morgan");
        bandNameStart.Add("Fly Project");
        bandNameStart.Add("Dice of Dixie Crew");
        bandNameStart.Add("Pepper Meshay");
        bandNameStart.Add("Judy Cheeks");
        bandNameStart.Add("Shary Bobbins");
        bandNameStart.Add("Jøe");
        bandNameStart.Add("Robert Mason");
        bandNameStart.Add("Dave Remington");
        bandNameStart.Add("Extasy Project");
        bandNameStart.Add("DJ Skribble");
        bandNameStart.Add("Gene Kardos");
        bandNameStart.Add("Brulux");
        bandNameStart.Add("Delaney & Bonnie & Friends");
        bandNameStart.Add("QED");
        bandNameStart.Add("Ido Bukelman");
        bandNameStart.Add("River Road");
        bandNameStart.Add("Ebony Evans");
        bandNameStart.Add("Raaban");
        bandNameStart.Add("Lynsey de Paul");
        bandNameStart.Add("Elisabeth Welch");
        bandNameStart.Add("Equitant");
        bandNameStart.Add("Stahlschlag");
        bandNameStart.Add("Bishop Edward L. Davis, Sr.");
        bandNameStart.Add("Nico Muhly");
        bandNameStart.Add("Bossasonic");
        bandNameStart.Add("Silent Stream of Godless Elegy");
        bandNameStart.Add("Billy Andrusco");
        bandNameStart.Add("Stefannie Bolarni");
        bandNameStart.Add("Mark Elf");
        bandNameStart.Add("Nach");
        bandNameStart.Add("Liz Robert");
        bandNameStart.Add("Negash Ali");
        bandNameStart.Add("Jerome");
        bandNameStart.Add("George Siravo");
        bandNameStart.Add("Catamenia");
        bandNameStart.Add("Why Knot");
        bandNameStart.Add("Aureole Trio");
        bandNameStart.Add("The Barbary Coast Guitar Duo");
        bandNameStart.Add("Wray Downes");
        bandNameStart.Add("Coco d'Or");
        bandNameStart.Add("Víctor Valverde");
        bandNameStart.Add("Rita Hayworth");
        bandNameStart.Add("Rudy Pérez");
        bandNameStart.Add("Dave Moody");
        bandNameStart.Add("Chords");
        bandNameStart.Add("La Locomotora Negra");
        bandNameStart.Add("Sharp Boys");
        bandNameStart.Add("Dark Globe");
        bandNameStart.Add("Gary Green");
        bandNameStart.Add("D.E.A. [Dead End Alliance]");
        bandNameStart.Add("Indio");
        bandNameStart.Add("Greg Pakstis");
        bandNameStart.Add("Misteur Valaire");
        bandNameStart.Add("Tootsie");
        bandNameStart.Add("Saens");
        bandNameStart.Add("Mario Winans");
        bandNameStart.Add("SF Merlo");
        bandNameStart.Add("Mary Ellis");
        bandNameStart.Add("Section Boyz");
        bandNameStart.Add("New York State Of The Art Jazz Ensemble");
        bandNameStart.Add("BTK");
        bandNameStart.Add("Prides");
        bandNameStart.Add("Paul Jones");
        bandNameStart.Add("The Hot 8 Brass Band");
        bandNameStart.Add("Donald Byrd");
        bandNameStart.Add("Los Rodhuiz");
        bandNameStart.Add("AD");
        bandNameStart.Add("Blak");
        bandNameStart.Add("Carl Fenton & His Orchestra");
        bandNameStart.Add("Hurricane");
        bandNameStart.Add("Christopher Walken");
        bandNameStart.Add("Russell Garcia & Strings");
        bandNameStart.Add("Scorched Earth");
        bandNameStart.Add("Harry Connick Jr. Quartet");
        bandNameStart.Add("Keri Johnsrud");
        bandNameStart.Add("Thomas Rheingans");
        bandNameStart.Add("Point of Grace");
        bandNameStart.Add("Geri Reischl");
        bandNameStart.Add("Crashdog");
        bandNameStart.Add("Paola Vanessa");
        bandNameStart.Add("Mr. Bugg");
        bandNameStart.Add("Mix'Usha");
        bandNameStart.Add("Joan Roberts");
        bandNameStart.Add("Sugar Daddy");
        bandNameStart.Add("Diane Kniss");
        bandNameStart.Add("Steve McConnell");
        bandNameStart.Add("Modern Jazz Tuba Project");
        bandNameStart.Add("Sarah Cracknell");
        bandNameStart.Add("Chico Mendoza");
        bandNameStart.Add("The Dreem Teem");
        bandNameStart.Add("Signed, Sealed and Delivered");
        bandNameStart.Add("The Castle Jazz Band");
        bandNameStart.Add("Tina Rose");
        bandNameStart.Add("Nina Persson");
        bandNameStart.Add("Fat Rat Da Czar");
        bandNameStart.Add("United Nations Project");
        bandNameStart.Add("MadeinTYO");
        bandNameStart.Add("Tim Hutton");
        bandNameStart.Add("Terror 2000");
        bandNameStart.Add("Icon for Hire");
        bandNameStart.Add("T Pop");
        bandNameStart.Add("Uptown Vocal Jazz Quartet");
        bandNameStart.Add("Ill Nature");
        bandNameStart.Add("SMiLE.dk");
        bandNameStart.Add("Shlomi Steps");
        bandNameStart.Add("Jonathan Higgins");
        bandNameStart.Add("Firescape");
        bandNameStart.Add("Fat Jon");
        bandNameStart.Add("David West");
        bandNameStart.Add("Lightning");
        bandNameStart.Add("J1 aka The Deer");
        bandNameStart.Add("Vinnie Moore");
        bandNameStart.Add("Nonononet");
        bandNameStart.Add("DJ Skylar");
        bandNameStart.Add("Fremont Fontenot");
        bandNameStart.Add("Abd Al Malik");
        bandNameStart.Add("Hazzard County Boys");
        bandNameStart.Add("Solido");
        bandNameStart.Add("Eddie Henderson");
        bandNameStart.Add("Carle Wooley");
        bandNameStart.Add("RIAS Big Band");
        bandNameStart.Add("Terrorfakt");
        bandNameStart.Add("Freedah Soul");
        bandNameStart.Add("Victor Marchese");
        bandNameStart.Add("Christine Siewert");
        bandNameStart.Add("Nevermore");
        bandNameStart.Add("Jimmy Beaumont");
        bandNameStart.Add("Point Blank Rage");
        bandNameStart.Add("Steve Bartek");
        bandNameStart.Add("DJ Pipes");
        bandNameStart.Add("Chris Murray");
        bandNameStart.Add("Helyne Stewart");
        bandNameStart.Add("Christi Warner");
        bandNameStart.Add("Walls of Jericho");
        bandNameStart.Add("The Brentwood Baptist Church Choir");
        bandNameStart.Add("Gianni Cazzola Trio");
        bandNameStart.Add("The Nu Beats");
        bandNameStart.Add("El Potro Alvarez");
        bandNameStart.Add("Rebecca Griffin");
        bandNameStart.Add("Alberto Askenazi");
        bandNameStart.Add("Los Suaves");
        bandNameStart.Add("Silence");
        bandNameStart.Add("Linq");
        bandNameStart.Add("Dusted");
        bandNameStart.Add("FreeFall Collective");
        bandNameStart.Add("Causeries");
        bandNameStart.Add("Pia Zadora");
        bandNameStart.Add("Uking Sukri");
        bandNameStart.Add("The Young Unknowns");
        bandNameStart.Add("Todd Osborn");
        bandNameStart.Add("Brandi Valentine");
        bandNameStart.Add("Hollywood Trombones");
        bandNameStart.Add("Krautschadl");
        bandNameStart.Add("Shy Child");
        bandNameStart.Add("Ardoin & McGee");
        bandNameStart.Add("Joe Val & The New England Bluegrass Boys");
        bandNameStart.Add("Banda Degollado");
        bandNameStart.Add("Chalino");
        bandNameStart.Add("Human Remains");
        bandNameStart.Add("So Elated");
        bandNameStart.Add("Vincent Gardner");
        bandNameStart.Add("Seth Lakeman");
        bandNameStart.Add("Joe Martino");
        bandNameStart.Add("MC Jazz");
        bandNameStart.Add("Red to Grey");
        bandNameStart.Add("Paul Leim");
        bandNameStart.Add("Nico Santos");
        bandNameStart.Add("Bizarre Inc.");
        bandNameStart.Add("Le Swing Quintette de Paris");
        bandNameStart.Add("The U.M.C.'s");
        bandNameStart.Add("Matthew Parker");
        bandNameStart.Add("Novus Rex");

        bandNameDecr = new List<string>();
        bandNameDecr.AddRange(bandNameStart);
    }

    public string getBandName()
    {
        int checkInd = Random.Range(0, bandNameDecr.Count);
        string retstring = bandNameDecr[checkInd];
        bandNameDecr.RemoveAt(checkInd);
        return retstring;
    }
}
